# Generated by Django 5.2 on 2025-12-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatmessage_chatattachment_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='flow',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='step',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='text_excerpt',
            field=models.TextField(blank=True),
        ),
    ]
