# Generated by Django 5.2 on 2026-02-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_promptset_activepromptconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='myapp.promptset'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_prompt_user_name'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('prompt_set', 'name'), name='uniq_prompt_set_name'),
        ),
    ]
