# Generated by Django 5.2 on 2026-02-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_prompt_unique_together_prompt_prompt_set_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prompt',
            name='uniq_prompt_user_name',
        ),
        migrations.RemoveConstraint(
            model_name='prompt',
            name='uniq_prompt_set_name',
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('prompt_set', 'name')},
        ),
        migrations.AddField(
            model_name='activepromptconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activepromptconfig',
            name='active_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.promptset'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='myapp.promptset'),
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='user',
        ),
    ]
