# Generated by Django 5.2 on 2026-02-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_prompt_uniq_prompt_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='myapp.promptset'),
        ),
    ]
